application: speedcoders
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "30d"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: frontend/\1
  upload: frontend/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: frontend/\1
  upload: frontend/(.*\.atom)
  expiration: "1h"

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: frontend/\1
  upload: frontend/(.*\.crx)

- url: /(.*\.css)
  mime_type: text/css
  static_files: frontend/\1
  upload: frontend/(.*\.css)

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: frontend/\1
  upload: frontend/(.*\.eot)

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: frontend/\1
  upload: frontend/(.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  static_files: frontend/\1
  upload: frontend/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: frontend/\1
  upload: frontend/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: frontend/\1
  upload: frontend/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: frontend/\1
  upload: frontend/(.*\.json)
  expiration: "1h"

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: frontend/\1
  upload: frontend/(.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: frontend/\1
  upload: frontend/(.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: frontend/\1
  upload: frontend/(.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: frontend/\1
  upload: frontend/(.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: frontend/\1
  upload: frontend/(.*\.otf)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: frontend/\1
  upload: frontend/(.*\.rss)
  expiration: "1h"

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: frontend/\1
  upload: frontend/(.*\.safariextz)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: frontend/\1
  upload: frontend/(.*\.(svg|svgz))

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: frontend/\1
  upload: frontend/(.*\.swf)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: frontend/\1
  upload: frontend/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: frontend/\1
  upload: frontend/(.*\.txt)

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: frontend/\1
  upload: frontend/(.*\.unity3d)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: frontend/\1
  upload: frontend/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: frontend/\1
  upload: frontend/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: frontend/\1
  upload: frontend/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: frontend/\1
  upload: frontend/(.*\.xml)
  expiration: "1h"

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: frontend/\1
  upload: frontend/(.*\.xpi)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: frontend/\1
  upload: frontend/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: frontend/\1
  upload: frontend/(.*\.(mid|midi|mp3|wav))  

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: frontend/\1
  upload: frontend/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: frontend/\1
  upload: frontend/(.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
- url: /(.+)/
  script: main.app

- url: /(.+)
  script: main.app

# site root
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html
  expiration: "15m"

libraries:
- name: webapp2
  version: "2.5.2"
